apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: CONTAINER_IMAGE
          env:
          - name: SQLALCHEMY_DATABASE_URI
            value: VAR_SQLALCHEMY_DATABASE_URI
          - name: AUTH0_USERNAME
            value: VAR_AUTH0_USERNAME
          - name: AUTH0_PASSWORD
            value: VAR_AUTH0_PASSWORD
          - name: AUTH0_CLIENT_ID
            value: VAR_AUTH0_CLIENT_ID
          - name: AUTH0_CLIENT_SECRET
            value: VAR_AUTH0_CLIENT_SECRET
          - name: AUTH0_CLIENT_ID_TEST
            value: VAR_AUTH0_CLIENT_ID_TEST
          - name: AUTH0_CLIENT_SECRET_TEST
            value: VAR_AUTH0_CLIENT_SECRET_TEST
          - name: AUTH0_DOMAIN
            value: VAR_AUTH0_DOMAIN
          - name: ALGORITHMS
            value: VAR_ALGORITHMS
          - name: API_AUDIENCE
            value: VAR_API_AUDIENCE
          - name: SECRET_KEY
            value: VAR_SECRET_KEY
          - name: SQLALCHEMY_TRACK_MODIFICATIONS
            value: "VAR_SQLALCHEMY_TRACK_MODIFICATIONS"
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:196397744326:certificate/7002d54c-868d-4fc4-842a-cd4694cf6d73
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    component: backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: https
      port: 443
      targetPort: 5000
  type: LoadBalancer
