---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo 'about to call dockerd'
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -LO https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl
      - curl -LO "https://dl.k8s.io/v1.27.1/bin/linux/amd64/kubectl.sha256"
      - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - python --version
      - echo 'export PATH=$PWD/:$PATH' >> $HOME/.bashrc
      - echo `kubectl version --short --client`
      - python -m pip install --upgrade --force pip
      - apt-get update && apt-get -y install jq  && pip install --upgrade awscli
  pre_build:
    commands:
      - TAG="$REPOSITORY_NAME.$REPOSITORY_BRANCH.$ENVIRONMENT_NAME.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI_BACKEND:$TAG"'@' backend_kubernetes.yml
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI_FRONTEND:$TAG"'@' frontend_kubernetes.yml
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI_BACKEND
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI_FRONTEND
      - export KUBECONFIG=$HOME/.kube/config
      - echo `ls -l`
  build:
    commands:
      - docker build -f ./backend/Dockerfile --tag $REPOSITORY_URI_BACKEND:$TAG ./backend
      - docker build -f ./frontend/Dockerfile --tag $REPOSITORY_URI_FRONTEND:$TAG ./frontend
  post_build:
    commands:
      - docker push $REPOSITORY_URI_BACKEND:$TAG
      - docker push $REPOSITORY_URI_FRONTEND:$TAG
      - echo $EKS_CLUSTER_NAME
      - echo $EKS_KUBECTL_ROLE_ARN
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --role-arn $EKS_KUBECTL_ROLE_ARN
      - kubectl apply -f backend_kubernetes.yml
      - kubectl apply -f frontend_kubernetes.yml
      - printf '[{"name":"backend","imageUri":"% s"},{"name":"frontend","imageUri":"%s"}]' $REPOSITORY_URI_FRONTEND:$TAG $REPOSITORY_URI_BACKEND:$TAG > build.json
artifacts:
  files: build.json
env:
  parameter-store:
    AUTH0_USERNAME: AUTH0_USERNAME
    AUTH0_PASSWORD: AUTH0_PASSWORD
    AUTH0_CLIENT_ID: AUTH0_CLIENT_ID
    AUTH0_CLIENT_SECRET: AUTH0_CLIENT_SECRET
    AUTH0_CLIENT_ID_TEST: AUTH0_CLIENT_ID_TEST
    AUTH0_CLIENT_SECRET_TEST: AUTH0_CLIENT_SECRET_TEST
    AUTH0_DOMAIN: AUTH0_DOMAIN
    ALGORITHMS: ALGORITHMS
    API_AUDIENCE: API_AUDIENCE
    SECRET_KEY: SECRET_KEY
    SQLALCHEMY_DATABASE_URI: SQLALCHEMY_DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS: SQLALCHEMY_TRACK_MODIFICATIONS
    REACT_APP_AUTH0_DOMAIN: REACT_APP_AUTH0_DOMAIN
    REACT_APP_AUTH0_CLIENT_ID: REACT_APP_AUTH0_CLIENT_ID
    REACT_APP_AUTH0_AUDIENCE: REACT_APP_AUTH0_AUDIENCE
