version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - REACT_APP_AUTH0_DOMAIN=dev-k1vtlssj33h7vu2e.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=i0Vd23NIEYHJshBp92y4QICLUugQG3es
      - REACT_APP_AUTH0_AUDIENCE=https://api.math
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend

  db:
      image: "postgres:13.4"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: math
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: